### ISSUE TITLE
Usar uma biblioteca para o RPC ao invés de invocar o bitcoin-cli

### ISSUE THREAD

**Issue by Davidson-Souza** [alex-btc/btc_on_chain_metrics#1]
Invocar o `bitcoin-cli` como child-process funciona, mas não é a melhor maneira de se fazer isso. Estamos assumindo que a máquina em questão TEM o bitcoin-cli (o que pode não ser verdade) e, além disso existe o overhead de invocar um comando, iniciar o linker, iniciar o bitcoin-cli e ai sim fazer o request. Acredito que uma biblioteca como o [python-bitcoin-rpc](https://pypi.org/project/python-bitcoinrpc/) faça um trabalho melhor.

**Comment by alex-btc** [comment]
Maravilha, vamos testar para ver ser fica mais rápido!

Aqui na minha máquina, quando rodei o ``rpc = RPC(...)``, com user e senha corretos, dá o seguinte erro:

```
     12     try:
     13       self.rpc = bitcoinrpc.authproxy.AuthServiceProxy(conString)
---> 14       self.getbestBlockhash()
     15     except ConnectionRefusedError:
     16       print ("Connection refused! Is your bitcoind running?")

<ipython-input-26-3d4eac5bde8c> in getbestBlockhash(self)
     38     except bitcoinrpc.authproxy.JSONRPCException:
     39       print("Authentication error. Check your credentials")
---> 40       exit(1)
     41   def getBlock(self, blockHash):
     42     if blockHash == None or len(blockHash) != 64:

TypeError: __call__() takes 1 positional argument but 2 were given
```

**Comment by alex-btc** [comment]
Consolidei todo o código no arquivo qtd_non_zero_addresses.py, ficou MUITO mais rápido usando a biblioteca rpc, MUITO OBRIGADO!

Aliás, se tiver interesse dá uma olhada em como ficou, se tem coisas a melhorar (não sou programador, deve ter muita coisa pra tornar o código mais profissional).

Vou fechar aqui, qualquer coisa me avisa.
